"""
Session-based authentication with bcrypt password hashing.

Credential sources (checked in order):
  1. credentials.yaml  — local file generated by setup_credentials.py
  2. st.secrets        — Streamlit Cloud Secrets panel (production)

Secrets format for Streamlit Cloud:
  [users.admin]
  name          = "Administrator"
  role          = "admin"
  password_hash = "$2b$12$..."   # bcrypt hash from setup_credentials.py

  [users.user]
  name          = "Regular User"
  role          = "user"
  password_hash = "$2b$12$..."

Roles:
  admin — access to chat + admin panel (upload docs, rebuild index)
  user  — access to chat only

Session state keys used:
  authenticated (bool), username (str), role (str), name (str)
"""
import os

import bcrypt
import streamlit as st
import yaml

CREDENTIALS_FILE = "credentials.yaml"


def _load_users() -> dict:
    # 1. Local credentials file (development / self-hosted)
    if os.path.exists(CREDENTIALS_FILE):
        with open(CREDENTIALS_FILE, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        return data.get("users", {})

    # 2. Streamlit Secrets (Streamlit Cloud deployment)
    try:
        users_secret = st.secrets.get("users", {})
        if users_secret:
            # Convert AttrDict to plain dict recursively
            return {k: dict(v) for k, v in users_secret.items()}
    except Exception:
        pass

    return {}


def _check_password(plain: str, stored_hash: str) -> bool:
    try:
        return bcrypt.checkpw(plain.encode(), stored_hash.encode())
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Public helpers called from each page
# ---------------------------------------------------------------------------

def is_authenticated() -> bool:
    return bool(st.session_state.get("authenticated"))


def is_admin() -> bool:
    return st.session_state.get("role") == "admin"


def logout():
    for key in ("authenticated", "username", "role", "name"):
        st.session_state.pop(key, None)
    st.rerun()


def require_auth():
    """
    Call at the top of every page.
    Shows the login form if the user is not authenticated, then stops execution.
    Returns normally (None) when the user IS authenticated.
    """
    if is_authenticated():
        return

    _render_login_form()
    st.stop()


def require_admin():
    """
    Call after require_auth() on admin-only pages.
    Shows an error and stops if the current user is not an admin.
    """
    if not is_admin():
        st.error("Access denied — admin role required.")
        st.stop()


# ---------------------------------------------------------------------------
# Login form (internal)
# ---------------------------------------------------------------------------

def _render_login_form():
    _, col, _ = st.columns([1, 2, 1])
    with col:
        st.markdown("## AI Governance Q&A")
        st.markdown("#### Please sign in to continue")
        st.divider()

        with st.form("login_form", clear_on_submit=False):
            username = st.text_input("Username", placeholder="username")
            password = st.text_input("Password", type="password", placeholder="••••••••")
            submitted = st.form_submit_button("Sign In", use_container_width=True)

        if submitted:
            users = _load_users()
            if not users:
                st.error(
                    "No credentials found. "
                    "Run `python setup_credentials.py` to create them."
                )
                return

            user_data = users.get(username)
            if user_data and _check_password(password, user_data.get("password_hash", "")):
                st.session_state["authenticated"] = True
                st.session_state["username"] = username
                st.session_state["role"] = user_data.get("role", "user")
                st.session_state["name"] = user_data.get("name", username)
                st.rerun()
            else:
                st.error("Invalid username or password.")
